image: node:lts-alpine

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  postalServer: 'mailhog-mailhog'

stages:
  - test
  - deploy
  - audit

test:
  stage: test
  services:
    - mailhog/mailhog:latest
  except:
  - schedules
  script:
  - yarn install --pure-lockfile --cache-folder .yarn
  - yarn test:ci
  coverage: '/^Statements\s*:\s*([^%]+)/'

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit