image: node:10

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - audit
  - deploy

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit
  
deploy:
  stage: deploy
  except:
  - schedules
  script:
    - echo "deploy setup pending"
  