image: node:lts-alpine

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test
  - deploy
  - audit
  
test:
  stage: test
  except:
  - schedules
  script:
    - echo "test setup pending"
  
deploy:
  stage: deploy
  except:
  - schedules
  script:
    - echo "deploy setup pending"

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit